---
- name: "dnf | Deploy dnf repos"
  ansible.builtin.yum_repository:
    async: "{{ repo['async'] | default(omit) }}"
    attributes: "{{ repo['attributes'] | default(omit) }}"
    bandwidth: "{{ repo['bandwidth'] | default(omit) }}"
    baseurl: "{{ repo['baseurl'] | default(omit) }}"
    cost: "{{ repo['cost'] | default(omit) }}"
    deltarpm_metadata_percentage: "{{ repo['deltarpm_metadata_percentage'] |
      default(omit) }}"
    deltarpm_percentage: "{{ repo['deltarpm_percentage'] | default(omit) }}"
    description: "{{ repo['description'] | default(omit) }}"
    enabled: "{{ repo['enabled'] | default(omit) }}"
    enablegroups: "{{ repo['enablegroups'] | default(omit) }}"
    exclude: "{{ repo['exclude'] | default(omit) }}"
    failovermethod: "{{ repo['failovermethod'] | default(omit) }}"
    file: "{{ repo['file'] | default(repo['name']) }}"
    gpgcakey: "{{ repo['gpgcakey'] | default(omit) }}"
    gpgcheck: "{{ repo['gpgcheck'] | default(omit) }}"
    gpgkey: "{{ repo['gpgkey'] | default(omit) }}"
    group: "{{ repo['group'] | default(omit) }}"
    http_caching: "{{ repo['http_caching'] | default(omit) }}"
    include: "{{ repo['include'] | default(omit) }}"
    includepkgs: "{{ repo['includepkgs'] | default(omit) }}"
    ip_resolve: "{{ repo['ip_resolve'] | default(omit) }}"
    keepalive: "{{ repo['keepalive'] | default(omit) }}"
    keepcache: "{{ repo['keepcache'] | default(omit) }}"
    metadata_expire: "{{ repo['metadata_expire'] | default(omit) }}"
    metadata_expire_filter: "{{ repo['metadata_expire_filter'] |
      default(omit) }}"
    metalink: "{{ repo['metalink'] | default(omit) }}"
    mirrorlist: "{{ repo['mirrorlist'] | default(omit) }}"
    mirrorlist_expire: "{{ repo['mirrorlist_expire'] | default(omit) }}"
    module_hotfixes: "{{ repo['module_hotfixes'] | default(omit) }}"
    mode: "{{ repo['mode'] | default(omit) }}"
    name: "{{ repo['name'] }}"
    owner: "{{ repo['owner'] | default(omit) }}"
    password: "{{ repo['password'] | default(omit) }}"
    priority: "{{ repo['priority'] | default(omit) }}"
    protect: "{{ repo['protect'] | default(omit) }}"
    proxy: "{{ repo['proxy'] | default(omit) }}"
    proxy_password: "{{ repo['proxy_password'] | default(omit) }}"
    proxy_username: "{{ repo['proxy_username'] | default(omit) }}"
    repo_gpgcheck: "{{ repo['repo_gpgcheck'] | default(omit) }}"
    reposdir: "{{ repo['reposdir'] | default(omit) }}"
    retries: "{{ repo['retries'] | default(omit) }}"
    s3_enabled: "{{ repo['s3_enabled'] | default(omit) }}"
    selevel: "{{ repo['selevel'] | default(omit) }}"
    serole: "{{ repo['serole'] | default(omit) }}"
    setype: "{{ repo['setype'] | default(omit) }}"
    seuser: "{{ repo['seuser'] | default(omit) }}"
    skip_if_unavailable: "{{ repo['skip_if_unavailable'] | default(omit) }}"
    ssl_check_cert_permissions: "{{ repo['ssl_check_cert_permissions'] |
      default(omit) }}"
    sslcacert: "{{ repo['sslcacert'] | default(omit) }}"
    sslclientcert: "{{ repo['sslclientcert'] | default(omit) }}"
    sslclientkey: "{{ repo['sslclientkey'] | default(omit) }}"
    sslverify: "{{ repo['sslverify'] | default(omit) }}"
    state: "{{ repo['state'] | default(omit) }}"
    throttle: "{{ repo['throttle'] | default(omit) }}"
    timeout: "{{ repo['timeout'] | default(omit) }}"
    ui_repoid_vars: "{{ repo['ui_repoid_vars'] | default(omit) }}"
    unsafe_writes: "{{ repo['unsafe_writes'] | default(omit) }}"
    username: "{{ repo['username'] | default(omit) }}"
  loop: "{{ vars['dnf_settings_repos'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "repo"
    label: "{{ 'Deploy DNF repo: ' ~ repo['name'] }}"
