---
- name: "dnf | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "dnf | Include repos tasks"
  ansible.builtin.include_tasks:
    file: "deploy_dnf_repos.yml"
  when:
    - "lookup('ansible.builtin.vars', 'dnf_settings_repos',
      default='') not in ['', [], '[]', None]"
- name: "dnf | Include dnf main settings tasks"
  ansible.builtin.include_tasks:
    file: "deploy_dnf.yml"
  when:
    - "lookup('ansible.builtin.vars', 'dnf_settings_main',
      default='') not in ['', [], '[]', None]"
- name: "dnf | Include dnf-versionlock tasks"
  ansible.builtin.include_tasks:
    file: "deploy_dnf_versionlock.yml"
  when:
    - "hostvars[inventory_hostname]['dnf'] is defined"
    - "hostvars[inventory_hostname]['dnf'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['dnf'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'dnf_versionlock_enable', default='')) == 'true'"
  vars:
    dnf_versionlock_enable: "[].versionlock[] |
      map(&enable || 'false', @) | [0]"
- name: "dnf | Include dnf-automatic tasks"
  ansible.builtin.include_tasks:
    file: "deploy_dnf_automatic.yml"
  when:
    - "lookup('ansible.builtin.vars', 'dnf_settings_automatic',
      default='') not in ['', [], '[]', None]"
