---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "deploy_dnf.yml"
  when:
    - "vars['dnf_settings_main'] is defined"
    - "vars['dnf_settings_main'] != []"
- ansible.builtin.include_tasks:
    file: "deploy_dnf_repos.yml"
  when:
    - "vars['dnf_settings_repos'] is defined"
    - "vars['dnf_settings_repos'] != []"
